version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 2305
      MYSQL_DATABASE: search_engine
      MYSQL_PASSWORD: 2305
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "8080:8080"

  app:
    image: openjdk:17
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8081"
    depends_on:
      - db
    command: java -jar target/SearchEngine-1.0-SNAPSHOT.jar